spring:
  data:
      mongodb:
            uri: mongodb://localhost/fameLive_dev
  rabbitmq.virtual-host: fameplus_dev
  rabbitmq.username: guest
  rabbitmq.password: guest
  rabbitmq.host: localhost

server:
  port: 8090
